# Generated by Django 4.0.4 on 2022-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_requeststatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=15, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='roles',
            field=models.CharField(choices=[('client', 'Client'), ('company', 'Company')], default='not defined', max_length=20),
        ),
    ]
