# Generated by Django 4.0.4 on 2022-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_requeststatus_status_alter_roles_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('canceled', 'Canceled')], max_length=15, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='roles',
            field=models.CharField(choices=[('company', 'Company'), ('client', 'Client')], default='not defined', max_length=20),
        ),
    ]
