# Generated by Django 4.0.4 on 2022-05-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_requeststatus_status_alter_roles_roles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending')], max_length=15, verbose_name='Request status'),
        ),
    ]
