# Generated by Django 4.0.4 on 2022-05-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_requeststatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('completed', 'Completed'), ('pending', 'Pending')], max_length=15, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='roles_id',
            field=models.CharField(choices=[('client', 'Client'), ('company', 'Company')], max_length=20),
        ),
    ]
