# Generated by Django 4.0.4 on 2022-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_requeststatus_status_alter_roles_roles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed')], max_length=15, verbose_name='Request status'),
        ),
    ]
