# Generated by Django 4.0.4 on 2022-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_title', models.CharField(max_length=200)),
                ('demo_description', models.CharField(max_length=200)),
            ],
        ),
    ]
